- pep257.py
- test_pep257.py
- tox.ini
> Added config file handling.

- docs/conf.py
- docs/release_notes.rst
- requirements/docs.txt
And minor edits in doc contents.
> Automatic links to GitHub issues in docs

- pep257.py
- test.py
- tox.ini
> Use function definitions instead of lambdas

- pep257.py
Fixes #108 by properly modifying `dirs` in place.
> match_dir fix

- docs/snippets/cli.rst
- pep257.py
- test_pep257.py
> Improve --convention flag

- docs/release_notes.rst
- setup.py
- src/pep257
- src/tests/test_pep257.py
> Use setuptools' entry_points to create the console script.

- docs/release_notes.rst
- src/pep257.py
- src/tests/test_cases/nested_class.py
- src/tests/test_definitions.py
> Handle publicity of nested classes

- docs/release_notes.rst
- setup.py
- src/pydocstyle/cli.py
- src/tests/test_integration.py
Fixes #216.
Still need to update docs.
> Remove `pep257` entry point (drop backward compatibility)

- docs/release_notes.rst
- docs/snippets/publicity.rst
- src/pydocstyle/checker.py
- src/tests/test_cases/superfluous_quotes.py
- src/tests/test_definitions.py
Solved superfluous quote problem in the beginning of the docstring from #166.
> Incorporated superfluous quote checking to D300.

- docs/release_notes.rst
- src/pydocstyle/cli.py
- src/pydocstyle/config.py
- src/tests/test_integration.py
> Added --config flag

- docs/release_notes.rst
- src/pydocstyle/violations.py
- src/tests/error_tests.py
- tox.ini
This is an improvement on #257 with added tests.
Thanks to @brbsix for the original PR.
> Fix --source option

- .travis.yml
- README.rst
- docs/release_notes.rst
- requirements/docs.txt
- tox.ini
- Enabled tests in ``tox.ini`` and ``.travis.yml``
- Declare support for 3.6 in ``README.rst`` and ``docs/release_notes.rst``
> Declare Python 3.6 support

- .appveyor.yml
- README.rst
> Adding appveyor

- .appveyor.yml
- src/tests/test_integration.py
> Add pypy to windows ci

- .appveyor.yml
- .travis.yml
- tox.ini
> Adding dist installation tests to CI

- .appveyor.yml
- .travis.yml
- README.rst
- docs/index.rst
- docs/release_notes.rst
- setup.py
- src/tests/test_integration.py
- tox.ini
> Drop support for python3.3 and fix broken build

- PULL_REQUEST_TEMPLATE.md
- docs/snippets/cli.rst
- src/pydocstyle/data/imperatives.txt
- src/tests/test_cases/test.py
- src/tests/test_integration.py
> Spelling fixes

- docs/snippets/cli.rst
- src/pydocstyle/config.py
> Add regex docs

- docs/snippets/config.rst
> Fixed `match` option in config file docs.

- docs/conf.py
- src/pydocstyle/checker.py
- src/pydocstyle/cli.py
- src/pydocstyle/config.py
- src/pydocstyle/parser.py
- src/pydocstyle/violations.py
- src/tests/test_cases/expected.py
- src/tests/test_cases/nested_class.py
- src/tests/test_decorators.py
- src/tests/test_definitions.py
- src/tests/test_integration.py
Upgraded Python syntax with [`pyupgrade --py3-plus`](https://github.com/asottile/pyupgrade).
---
> Upgrade Python syntax with pyupgrade --py3-plus

- requirements/tests.txt
- src/pydocstyle/__main__.py
- src/pydocstyle/violations.py
- src/pydocstyle/wordlists.py
Adding type hints to the codebase.
> Type Hints!

- .pre-commit-hooks.yaml
- docs/conf.py
- docs/release_notes.rst
- docs/snippets/pre_commit.rst
- docs/usage.rst
- hooks.yaml
> Add pre-commit hook #346

- src/tests/parser_test.py
> Added simple fstring parsing testcase

- docs/error_codes.rst
> [DOCONLY] Document that pep257 mode disables D413

- src/pydocstyle/checker.py
- src/pydocstyle/cli.py
- src/pydocstyle/parser.py
- src/pydocstyle/wordlists.py
- src/tests/test_integration.py
> Fix bug in PEP257 conformance test, and fix docstring violations

- setup.py
Background info at
https://github.com/pypa/warehouse/pull/7882#issue-412444446
> Add Release Notes project URL

- .github/workflows/test.yml
- tox.ini
Appveyor and Travis have been very slow lately. Github actions on the other hand provides an easy and fast way to test on all of our supported platforms.
> Use Github Actions for testing

- docs/release_notes.rst
- src/pydocstyle/checker.py
- src/tests/test_cases/functions.py
> Fix IndexError on strange backslash docstring

- README.rst
- pyproject.toml
- requirements/tests.txt
- src/pydocstyle/__init__.py
- src/pydocstyle/__main__.py
- src/pydocstyle/checker.py
- src/pydocstyle/cli.py
- src/pydocstyle/config.py
- src/pydocstyle/parser.py
- src/pydocstyle/utils.py
- src/pydocstyle/violations.py
- src/pydocstyle/wordlists.py
- tox.ini
> Blacken the source code and sort imports

- docs/release_notes.rst
Just updating the release notes for  #499 that i forgot to update last time.
> update release notes for #499

- .github/workflows/test.yml
- src/tests/test_integration.py
> Fix failing windows tests

- docs/release_notes.rst
- src/pydocstyle/violations.py
> fix `--source`

- requirements/docs.txt
> requirements/docs.txt: Use current versions of Jinja2 and sphinx

- docs/index.rst
> Docs: pydocstyle supports Python 3.7 through 3.11.

- .pre-commit-hooks.yaml
> Revert "fix: do not pass file names with pre-commit"
