PyCQA/pydocstyle

README.rst, pep257.py, test_pep257.py
=> Added `--count` flag.

pep257.py
by always setting the log level, you enforce that log level on every
project that attempts to depend on the pep257 module.  instead logging
should be enabled for debug when needed.
this fixes a bug in the flake8-docstrings plugin for flake8
=> remove loglevel config from module

docs/snippets/error_code_table.rst, pep257.py, test.py
The previous implementation checked that at least one blank line existed
between the summary line and the detail section for a multi-line
docstring, but multiple separating blank lines were also allowed.
=> Validate only one blank between summary and detail

pep257
When using `pep257` without rewriting the hashbang in the script (e.g. via `tox`), the space at the beginning of the hashbang breaks invocation of the script:
```
pep257 runtests: commands[0] | /home/buildbot/slave/lint/build/.tox/pep257/bin/pep257 ...
: No such file or directory
```
=> Fix hashbang in pep257 script.

pep257.py, test_pep257.py, tox.ini
Without this, e.g. checking an UTF-8 file (with `# encoding=utf-8`) on Windows
with Python 3 is broken (`UnicodeDecodeError`) because it's read as latin1.
=> Use tokenize.open to open files.

pep257.py, test_pep257.py
=> Allow docstrings given as raw unicode (ur""")

pep257.py
Improves the error message when encountering an unexpected token kind in `__all__`
=> Better error message for wrong token kind in __all__

docs/conf.py, docs/release_notes.rst, pep257.py, test_pep257.py
=> D104: Missing docstring in public package

docs/release_notes.rst, src/pep257.py, src/tests/test_definitions.py
=> Fixed the creation of an AllError when there is an unexpected token

src/pep257.py
The collect function was removed in a0dcb0c2,
however it was not removed from `__all__`.
=> Remove `collect` from `__all__`

docs/snippets/config.rst, src/pep257.py
PEP8 and PyLint use `.pep8rc` and `.pylintrc`, respectively, so I thought it would be good for PEP257 to support the “rc” convention as well.
=> Support '.pep257rc' as a configuration filename

src/pep257.py
=> Fix: __all__ should be a tuple

src/pep257.py, src/tests/test_definitions.py
The __future__ import parser introduced in 0.7.0 would cause
pep257 to crash with an AssertionError for some obscure
valid syntax, and many invalid syntax.
Fixes #153.
=> Prevent AssertionError parsing __future__ import

src/pep257.py
bbaadb4b introduced `check_blank_before_after_class` with
`slef` as the first parameter instead of `self` as used
throughout the module.
=> Replace slef with self

src/pep257.py
py.test emits a warning when state is modified during an assert,
as py.test attempts to inspect the variables within an assert.
Also add a docstring for Parser.consume.
=> Stabilise state during Parser.consume assert

docs/release_notes.rst, src/pep257.py, src/tests/test_cases/capitalization.py, src/tests/test_cases/comment_after_def_bug.py, src/tests/test_definitions.py, src/tests/test_pep257.py
The new error is turned on by default.
=> Added D403: First word of first line should be properly capitalized

.travis.yml, README.rst, src/pep257.py, src/tests/test_cases/capitalization.py, src/tests/test_cases/test.py, src/tests/test_pep257.py, tox.ini
=> Make D403 weaker to avoid false positives

docs/release_notes.rst, src/pydocstyle.py, src/tests/test_cases/test.py
While PEP 257 suggests to use lowercase literals, Python allows uppercase literals as string prefixes.
Unlike D301 and 302, error code D300 is not reported if uppercase docstring prefixes are being used (e.g., `R'''...'''`). The current implementation of D300 also causes a false positive for uppercase literals with double quotes (e.g., `R"""Sum\\mary."""`), and detects the quotes incorrectly for a `ur'''...'''` docstring prefix. 
This proposes a more robust implementation for D300 and adds some uppercase tests for D301 and ~~D302~~, which they already pass.
EDIT: For the sake of simplicity, the D302 uppercase literal test will be included in another PR.
=> Consider uppercase docstring prefixes at D300.

docs/error_codes.rst, docs/release_notes.rst, src/pydocstyle.py, src/tests/test_cases/multi_line_summary_start.py, src/tests/test_cases/test.py, src/tests/test_definitions.py, src/tests/test_integration.py
Hello,
PEP 257 allows multi-line docstring summaries to start on the first or second line, as it is outlined in #44. I prefer one over the other and was looking for a way to perform consistency checks on my projects. Thus, I have added two optional error codes (D212, D213), which you might like to incorporate.
As those are more restrictive than PEP 257, both error codes should naturally be selected explicitly (and typically mutual exclusive) by the following. Otherwise, they are ignored.
```
pydocstyle --add-select=D212,D213 file_to_check.py
```
I have tried to touch as little as possible when implementing them. Please review if this is too cumbersome, or interferes with pydocstyle in a way I have not noticed.
Kind regards,
Tobias
=> Optional checks for multi-line docstring summary style.

src/pydocstyle.py, src/tests/test_cases/test.py, src/tests/test_definitions.py, src/tests/test_integration.py, tox.ini
This leads to problems for tools integrating with pydocstyle, e.g., atom
linter-pydocstyle
Closes #179 
cc @BrnoPCmaniak
=> Stop converting the filename to lowercase

src/pydocstyle.py
The couple times that run_pydocstyle is used calls it with "use_pep257"
instead of "used_pep257". This makes it consistent by using the active
present-tense voice instead of the past-tense voice.
=> Match argument to passed in keyword argument

docs/error_codes.rst, docs/release_notes.rst, src/pydocstyle.py, src/tests/test_cases/unicode_literals.py, src/tests/test_decorators.py, src/tests/test_definitions.py, tox.ini
This is intended to make docstrings shorter and to the point, as they should not start with "This module contains [..]" or "This class represents [..]".
It is unchecked by default as it is not part of the PEP257 standard.
=> Added D404: First word of the docstring should not be `This`

docs/release_notes.rst, src/pydocstyle.py, src/tests/test_cases/all_import.py, src/tests/test_cases/all_import_as.py, src/tests/test_cases/all_import_aux.py, src/tests/test_definitions.py
=> Proper parsing of imports to avoid misunderstanding __all__ imports

.travis.yml, README.rst, docs/index.rst, docs/release_notes.rst, setup.cfg, src/pydocstyle/config.py, src/pydocstyle/parser.py, src/pydocstyle/utils.py, src/pydocstyle/violations.py, src/tests/test_cases/expected.py, src/tests/test_definitions.py, src/tests/test_integration.py, tox.ini
=> Drop support for Python 2.6.

docs/release_notes.rst, src/pydocstyle/parser.py, src/tests/test_definitions.py
This is a partial fix for #168. With this change, the parser no longer crashes on test file [E90.py](https://github.com/PyCQA/pep8/blob/fed43c5/testsuite/E90.py).
Note that this is a pretty minimal fix. A potential future refactor to increase the robustness of the parser could be to use the null-object pattern and return a NullToken from `TokenStream.move` instead of `None`. In this way, any code that consumes `TokenStream.current` doesn't have to null-check the property value explicitly which should make the other issues mentioned in #168 go away.
=> Ignore SyntaxError while parsing

docs/release_notes.rst, docs/snippets/cli.rst, docs/snippets/config.rst, src/pydocstyle/checker.py, src/pydocstyle/cli.py, src/pydocstyle/config.py, src/tests/test_cases/test.py, src/tests/test_definitions.py
@Nurdok I think you talked about adding an option like this, see if it's what you have in mind. A user can now do e.g.:
```
--ignore-decorators=wraps
```
Or in my case, I will add this to my config:
```
ignore-decorators = copy_.*_doc_to_.*
```
=> Allow skipping decorated functions

src/pydocstyle/cli.py, src/pydocstyle/parser.py, src/tests/test_integration.py
=> Print errors to stdout

docs/release_notes.rst, docs/snippets/cli.rst, src/pydocstyle/config.py, src/tests/test_integration.py
An attempt at implementing the request in #72 
Suggestions on how to succinctly document this in the help output would be appreciated.
=> Support pycodestyle style wildcards.

.gitignore, .travis.yml, README.rst, docs/index.rst, docs/release_notes.rst, tox.ini
PyPy3 currently only implements the equivalent of CPython 3.2, which we don't support. Pip has also dropped support for PyPy3, resulting in the following build error:
```
/home/travis/virtualenv/pypy3-2.4.0/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py:83: UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here.
pip requires Python '>=2.6,!=3.0.*,!=3.1.*,!=3.2.*' but the running Python is 3.2.5
```
Support for PyPy3 will be restored when it is supported by Pip, and when it will implement a newer equivalent version for CPython (3.3 or higher).
=> Drop pypy3 (temporarily)

docs/error_codes.rst, docs/release_notes.rst, docs/snippets/publicity.rst, src/pydocstyle/parser.py, src/tests/parser_test.py
=> Modules starting with a single leading underscore are considered private

docs/snippets/publicity.rst, src/pydocstyle/parser.py, src/tests/test_definitions.py
=> Remove warning when __all__ is a list

docs/snippets/config.rst, src/pydocstyle/config.py
Supporting configuration files with the `.ini` extension means that many editors will support syntax highlighting out-of-the-box without needing an additional plugin or settings tweak.
=> Allow file extensions on config files

src/pydocstyle/parser.py, src/tests/parser_test.py
=> Added matrix multiplication operator handling

src/pydocstyle/checker.py
Some tools like prospector tried to import a v1 pydocstyle or a v2 pydocstyle and
uses them the same way, BUT there has been a breaking change introduced here and so
`ignore_decorators` must be provided. This breaks at least prospectors behavior. 
May we set just a default=None value to have the same signature for the v1 and v2 function here.
=> Default value for breaking API change.

docs/release_notes.rst, src/pydocstyle/checker.py, src/pydocstyle/violations.py, src/tests/test_cases/nested_class.py, src/tests/test_cases/test.py
Currently D101 covers both classes and nested classes. This is a problem if you want to exclude e.g. a Meta nested class from needing a docstring.
In this pull request I put Nested Classes that miss a docstring under D106. This allows me to configure pydocstyle to check for D101, but exclude the D106 situation.
This problem is also discussed at: https://github.com/PyCQA/pydocstyle/issues/198
=> Mark missing docstrings for nested classes as violation D106

docs/release_notes.rst, src/pydocstyle/checker.py, src/pydocstyle/parser.py, src/pydocstyle/violations.py, src/tests/test_cases/test.py
As described in #273, it would be useful to have a separate error code for missing docstrings on `__init__` methods (which currently fall under `D102`).
This PR introduces `D107` for this purpose.
This enables the user to use only class docstrings (as described by [this Google style](https://github.com/sphinx-doc/sphinx/blob/1.6.3/doc/ext/example_google.py#L201-L205)) by ignoring `D107`.
=> Introduce D107 code for missing __init__ docstring

docs/release_notes.rst, src/pydocstyle/cli.py, src/pydocstyle/config.py, src/tests/test_integration.py
=> Print a warning where error code (/prefix) doesn't exist, e.g., --select=D9

docs/release_notes.rst, requirements/runtime.txt, setup.py, src/pydocstyle/config.py, src/tests/test_integration.py
=> #250 - Added support for multi-lined config entries

docs/release_notes.rst, src/pydocstyle/config.py
=> Better help section

docs/release_notes.rst, src/pydocstyle/violations.py, src/tests/test_integration.py
=> #273 - Removing D107 from numpy default violations

docs/release_notes.rst, src/pydocstyle/parser.py, src/pydocstyle/violations.py, src/tests/parser_test.py
Add `.start` and `.end` attributes to docstring objects that hold the starting and ending line numbers of the docstring token. Docstring was changed to a subclass of str to allow this, ensuring backwards compatibility.
Add a property `.error_lineno` to Definition. This will use the docstring's line number if it exists, or the definition's line number otherwise.
Finally, switch `Error` to use the new `.error_lineno` property.
Tested on Python 2.7, 3.3-3.5 and PyPy with Tox.
=> Report docstring content violations on docstring line (fixes #83)

docs/error_codes.rst, docs/release_notes.rst
The file `error_codes.rst` had information that specified the pep257 default convention, but lacked information about the numpy convention.  I updated this section of the docs with the conventions specified at the end of `src/pydocstyle/violations.py`, which presently are:
```Python
conventions = AttrDict({
'pep257': all_errors - {'D203', 'D212', 'D213', 'D214', 'D215', 'D404',
'D405', 'D406', 'D407', 'D408', 'D409', 'D410',
'D411'},
'numpy': all_errors - {'D107', 'D203', 'D212', 'D213', 'D402', 'D413'}
})
```
=> Update information on pep257 & numpy conventions

src/pydocstyle/config.py
That's not really a bug or feature, so I did not add tests or line in changelog.
=> update log.warn (deprecated) to log.warning

docs/release_notes.rst, src/pydocstyle/checker.py, src/tests/test_cases/sections.py, tox.ini
Solves #311.
The problem was that the regex split words when reached an underscore, so "arguments_bla" was caught as "arguments".
=> Fix false-positive D405 recognition

docs/release_notes.rst, src/pydocstyle/parser.py
=> Fix newline exception

src/pydocstyle/config.py, src/pydocstyle/violations.py
- Renamed some variables to eliminate interfering between different scopes and builtin names.
- Changed an ugly `if` to a less ugly `if`.
- Added `conventions` to `__all__` since it's imported elsewhere.
=> Lint fixes

.appveyor.yml, README.rst, docs/index.rst, docs/release_notes.rst, setup.py, tox.ini
The next version of pydocstyle will support Python 3.4+ only. Support for PyPy3 should also be added to the next release in a different PR.
This PR only removes Python 2.7 from the docs and CI tools - the actual refactoring of the source code will happen over time (removing `six`, using Python 3 features, etc.)
=> Drop support for Python 2.7 and PyPy

.appveyor.yml, requirements/tests.txt, setup.py, src/pydocstyle/__init__.py, src/pydocstyle/checker.py, src/pydocstyle/config.py, src/pydocstyle/parser.py, src/pydocstyle/utils.py, src/tests/parser_test.py, src/tests/test_decorators.py, src/tests/test_integration.py
There's still `six` use in tests to check for Python 3.4.
=> Remove `six` from production code and other Python 2/3 compatibility imports

.gitignore, requirements/tests.txt, src/pydocstyle/checker.py, src/pydocstyle/cli.py, src/pydocstyle/parser.py, src/pydocstyle/utils.py, src/pydocstyle/violations.py, src/tests/test_cases/sections.py, src/tests/test_cases/test.py, tox.ini
Added  the minimal code needed for typehint validation.
I also removed some whitespaces in tox.ini - it seems that tox doesn't remove them (for instance, py34 install env was called `py34- install`).
=> Introducing type hints

docs/release_notes.rst, src/pydocstyle/parser.py, src/tests/parser_test.py
=> fix parsing tuple syntax dunder all

src/pydocstyle/checker.py, src/pydocstyle/utils.py, src/tests/test_cases/test.py, src/tests/test_utils.py
Add an algorithm to choose the most appropriate imperative when there are multiple imperatives that stem to the same word.
=> Select best imperative by longest prefix match

docs/release_notes.rst, src/pydocstyle/checker.py, src/pydocstyle/utils.py, src/pydocstyle/violations.py, src/pydocstyle/wordlists.py, src/tests/test_cases/noqa.py, src/tests/test_cases/sections.py, src/tests/test_cases/test.py, src/tests/test_utils.py
=> D401: Allow multiple imperative forms of the same stem.

docs/release_notes.rst, src/pydocstyle/parser.py, src/tests/parser_test.py
=> fix parser dead loop when meet comment after __all__

docs/release_notes.rst, src/pydocstyle/checker.py, src/tests/test_integration.py
The `checker.get_function_args` function will fail with an IndentationError if it gets a `function_string` that is indented. This fixes that. :)
=> Fix IndentationError while parsing function

docs/release_notes.rst, src/pydocstyle/violations.py
=> Fix error table RST, max short code now over 69 chars

docs/error_codes.rst, docs/release_notes.rst, docs/snippets/cli.rst, src/pydocstyle/checker.py, src/pydocstyle/parser.py, src/pydocstyle/violations.py, src/tests/test_cases/expected.py, src/tests/test_cases/sections.py
This patch adds support for checking the Args section of
methods.
Closes #275
=> Add support for methods for Google style arg check

docs/release_notes.rst, src/pydocstyle/violations.py, src/tests/test_integration.py
=> Remove D413 from the pep257 convention

docs/release_notes.rst, src/pydocstyle/checker.py, src/pydocstyle/violations.py, src/tests/test_cases/sections.py
Hi! I got rather confused reading the docs about references to section names ending in _semicolons_. What's meant, and what D416 is actually checking for, is sections ending in _colons_. This PR just fixes those references. I don't _think_ this needs new tests, since it changes only the message, not the code or behaviour, but of course let me know if that's not correct :)
Make sure to include the PR number after you …
=> [DOCONLY] Fix misnamed D416 reference: `s/semicolon/colon/g`

docs/release_notes.rst, src/pydocstyle/checker.py, src/tests/test_cases/test.py
This adds a few exceptions to `D301: Use r""" if any backslashes in a docstring.`
Some backslashes are usually intended string formatting in docstrings and should not be escaped (directly or indirectly via a raw string). These include:
- Line continuations (c.f. #364).
- Unicode literals `\u...` and `\N...`.
Closes #364.
--- …
=> D301 exceptions

docs/release_notes.rst, src/pydocstyle/parser.py, src/tests/parser_test.py
Fixes #410
The bug existed because we were not accounting for cases which should
be treated as a logical new line.
=> Fix decorator parsing

docs/release_notes.rst, src/pydocstyle/checker.py, src/pydocstyle/violations.py, src/tests/test_cases/sections.py
=> Extend support for detecting missing arguments in Numpy style   docstrings

.appveyor.yml, .travis.yml, docs/release_notes.rst, setup.py, tox.ini
* Added support for Python 3.8. This will only be tested in Travis, since AppVeyor don't support it yet.
* Added to release notes and setup.py.
* Nit: Changed the order of the build matrix so each version would be together, not grouped by test/install.
=> Support py38

docs/error_codes.rst, docs/release_notes.rst, src/pydocstyle/checker.py, src/pydocstyle/config.py, src/tests/test_cases/sections.py
This solves #388 
The problem was that the same docstring could be recognized as both google and numpy.
I changed it so numpy takes precedence since it's easier to detect.
=> Fix section mix bug

docs/release_notes.rst, src/pydocstyle/parser.py, src/tests/test_cases/noqa.py
=> Allow skip on module level messages

docs/release_notes.rst, src/pydocstyle/config.py, src/tests/test_integration.py
This allows to specify e.g. "ignore" on multiple lines, without adding
additional commas:
[pydocstyle]
ignore = D100,D101,D102,D103,
D203,
D213,
Continuation of https://github.com/PyCQA/pydocstyle/pull/221.
=> Strip whitespace in _fix_set_options

docs/release_notes.rst, src/pydocstyle/checker.py, src/tests/test_cases/test.py
=> Fix the AttributeError bug when parsing parameter lists in a class docstring

docs/release_notes.rst, src/pydocstyle/config.py
With Python 3.6+ the `\.` in the string literals results in a `DeprecationWarning` or `SyntaxError` (in later Python versions or when using `-W error`).
=> fix invalid escape sequence

docs/release_notes.rst, src/pydocstyle/checker.py, src/tests/test_cases/sections.py
These arguments have been marked private. As such,
it should be okay for the checker to not validate their
existence in the docstring,
Fixes #438
=> Skip function arguments prefixed with `_` in D417 check

docs/error_codes.rst, docs/release_notes.rst, docs/snippets/cli.rst
Addresses the problem I noted in a comment on issue #380
=> Update conventions documentation for v4.0.0

docs/release_notes.rst, src/pydocstyle/checker.py, src/tests/test_cases/functions.py
Hello, and thanks for the great tool!
This small PR fixes the case of detecting asynchronous inner functions, for D202 (inner classes and functions require an empty line between the outer function docstring and them). It is a follow-up of #426.
=> fix: regex to catch inner functions doesn't catch asynchronous ones

docs/release_notes.rst, src/pydocstyle/checker.py, src/tests/test_cases/sections.py
Currently, due to the way the regex was specified, the regex
matcher was getting thrown off by types that used colons.
This change makes the regex robust to such type and fixes #443
=> Fix bug with google style arg regex

src/pydocstyle/config.py
I recently went over [Matplotlib](https://github.com/matplotlib/matplotlib/pull/16706), [Pandas](https://github.com/pandas-dev/pandas/pull/32322) and [NumPy](https://github.com/numpy/numpy/pull/15731), fixing a small mistake in the way that Python 3's exception chaining is used. I searched this repo, and found just one instance of this mistake.
The mistake is this: In some parts of the code, an exception is being caught and replaced with a more user-friendly error. In these cases the syntax `raise new_error from old_error` needs to be used.
Python 3's exception chaining means it shows not only the traceback of the current exception, but that of the original exception (and possibly more.) This is regardless of `raise from`. The usage of `raise from` tells Python to put a more accurate …
=> Fix exception cause in config.py

README.rst
Fixes #457
Added new updated link to `pydocstyle’s` documentation (old link is now deprecated)
=> Added updated link to pydocstyle’s documentation

docs/release_notes.rst, src/pydocstyle/checker.py, src/tests/test_cases/expected.py, src/tests/test_cases/sections.py
In order to determine the missing arguments, we currently
use ast.parse to parse partial source code. This parsing
might lead to syntax errors. We catch the syntax error and
make the parsing more resilient to errors in the source code.
Fixes #437
=> Fix indentation error while parsing class methods

docs/release_notes.rst, src/pydocstyle/checker.py, src/tests/test_cases/sections.py
- Dedent the function definition before parsing it.
- Join continued-lines before attempting to parse the docstring.
Alternative to #441; further improves handling of parameter descriptions with continued lines (which were not handled correctly before).
=> Fix handling of dedented continuation lines.

.github/workflows/test.yml, requirements/tests.txt, tox.ini
Python 3.9 is out in October, with rc1 now available, and it's strongly recommended to test against it now to make sure libraries work, and also to help test 3.9 itself.
There was an error running mypy:
```
py39 run-test: commands[1] | mypy --config-file=tox.ini src/
src/pydocstyle/utils.py:25: error: syntax error in type comment
Found 1 error in 1 file (checked 35 source files)
ERROR: InvocationError for command /private/tmp/pydocstyle/.tox/py39/bin/mypy --config-file=tox.ini src/ (exited with code 2)
```
This looks like it was fixed in mypy in https://github.com/python/mypy/pull/8716, and released in mypy v0.780. So let's upgrade to use the newest 0.782.
---
If you've added an error code or changed an error …
=> Test on Python 3.9-dev

.github/workflows/test.yml, README.rst, docs/conf.py, docs/index.rst, docs/release_notes.rst, setup.py, src/pydocstyle/checker.py, src/pydocstyle/config.py, src/pydocstyle/parser.py, src/pydocstyle/violations.py, src/tests/parser_test.py, src/tests/test_cases/canonical_google_examples.py, src/tests/test_cases/noqa.py, src/tests/test_cases/test.py, src/tests/test_cases/unicode_literals.py, src/tests/test_definitions.py, src/tests/test_integration.py, tox.ini
Fixes #508.
Also upgrades Python syntax with `pyupgrade --py36-plus`
And removes D302, which is redundant and cannot be run now Python 2 is dropped.
---
=> Drop support for Python 3.5

docs/release_notes.rst, docs/snippets/config.rst, requirements/runtime.txt, setup.py, src/pydocstyle/config.py, src/tests/test_integration.py
This PR closes #447.
- Fix a small unrelated bug, where inline comments in `.ini` files behaved differently when autodetected by `_get_config_file_in_folder` and when manually specified by `--config`.
- Add `toml` as a package dependency (`setup.py`) and as a pinned runtime dependency (`requirements/runtime.txt`).
- Implement `TomlParser` - a thin wrapper around the `toml` library with minimal API parity with `RawConfigParser`.
- Autodetect `pyproject.toml` configuration
- Autodetect `tool.pydocstyle` section
- Implement error code list support for `toml`. This is so that you can use
```toml
select = [
"D100",
"D103",
]
```
and not only
```toml
select = "D100,D103"
```
- Almost all tests in `test_integration.py` which used the `env` fixture now are run for both `toml` and `ini` versions …
=> Enable full `toml` configuration and `pyproject.toml`

.bumpversion.cfg, .github/workflows/test.yml, docs/release_notes.rst, setup.py, src/pydocstyle/utils.py, tox.ini
This reverts commit f710d32431fa5662e8c08c305d699e506c240f0b.
This closes #540.
=> Fix CI for python 3.6

README.rst
According to the badge on the README Python 3.9 is supported and 3.9 is tested in CI, but it is not listed as being supported in the text of the README so I added it there.
=> Updating readme to reflect support for Python 3.9

docs/release_notes.rst, docs/snippets/config.rst, src/pydocstyle/checker.py, src/pydocstyle/cli.py, src/pydocstyle/config.py, src/pydocstyle/parser.py, src/tests/test_cases/test.py, src/tests/test_definitions.py
This addresses issue #531. It excludes any method decorated with a decorator with "property" in the name in order to catch `cached_property` and other custom property types. Maybe there’s a fancier way of doing this, but I don’t know what it is.
=> Exempt properties from D401

requirements/tests.txt
This commit updates the dependencies for mypy and black to the latest version to fix ast issues with python 3.10
=> Fix CI for python 3.10

docs/release_notes.rst, src/pydocstyle/checker.py, src/pydocstyle/violations.py, src/tests/test_cases/capitalization.py, src/tests/test_cases/test.py
Reporting D10X errors for empty docstrings is doubly misleading:
1. The docstring _isn't_ missing. It's _empty_.
2. The D10X errors use _public_, but could be reported on private definitions.
=> Add D419: Add and switch to "Docstring is empty" error code

docs/release_notes.rst, requirements/tests.txt, src/pydocstyle/checker.py, src/tests/test_cases/sections.py
=> Allow for hanging indent when documenting args in Google style

docs/release_notes.rst, src/pydocstyle/config.py, src/tests/test_integration.py
Fixes #549.
This uses `os.path.basename` before trying to match against the pattern set in `--match` option. This way, even if full paths to files are passed to `pydocstyle` (by VSCode, for example), only filename part of the path will be matched with the set pattern, thereby eliminating accidental matches with the path. This is also more consistent with how `--match` is documented previously.
Make sure to include the …
=> Fix match option to only consider basename when given a path argument

docs/error_codes.rst
The double-dash for command line option `--convention` was being converted to an en-dash.
I'm not very familiar with RST, but this change seems correct. By all means reject if not.
=> docs: Fix double-dash converted to en-dash

docs/conf.py, pyproject.toml, src/tests/test_integration.py, tox.ini
---
I ran the tests locally when I noticed some pytest warnings:
```python
.tox/py36-tests/lib/python3.6/site-packages/_pytest/config/__init__.py:1233
/Users/ahedges/projects/personal/pydocstyle/.tox/py36-tests/lib/python3.6/site-packages/_pytest/config/__init__. …
```
=> Fix test warnings and improve lint configuration

requirements/docs.txt, requirements/tests.txt
---
CI was failing for 03404c81b2ccf57248032af3cdb11f6b4d1e5a63 because of two problems:
- Black was failing from <https://github.com/psf/black/issues/2964>. Updating Black to the latest version fixes it without reformatting any of the code.
- Sphinx was failing …
=> Fix broken CI checks

pyproject.toml, tox.ini
=> Move tool configs to pyproject.toml

.github/workflows/release.yml
This permit to release on pypi if a value for ``PYPI_API_TOKEN`` is set in github settings. The release is done when a release is created/published in github interface.
Relates to #575
=> Add github action to be able to release on published tag

docs/release_notes.rst, poetry.lock, pyproject.toml, requirements/runtime.txt, requirements/tests.txt, src/pydocstyle/config.py
Use the built-in `tomllib` module in Python 3.11 and the modern `tomli` package in older Python versions to read .toml configs instead of the unmaintained and broken `toml` package.
Fixes #599
Fixes #600
---
=> Use tomllib/tomli for reading .toml configs

docs/release_notes.rst, src/pydocstyle/checker.py, src/tests/test_cases/sections.py
Closes #618.
I'm not really happy about this heuristic, but it seems to do the work. It would be cleaner change the splitting of docstring to sections, but I'm afraid its not possible in general case due to `numpy` style having no indent. Anyway, this should fix the problem with `google` style convention and additional lines being considered part of the section.
The solution may not work in mixed tabs/spaces docstring where each line has different whitespace prefix, but I find this to be pretty obscure case (and it's obviously not covered by `pydocstyle` tests anyway).
=> Fix false positive of google convention missing args descriptions
